# generated by datamodel-codegen:
#   filename:  Accounts/AccountsRequest.json

from __future__ import annotations
from architect_py.grpc_client.Accounts.AccountsResponse import AccountsResponse

from typing import Annotated, Optional

from msgspec import Meta, Struct

from .. import definitions


class AccountsRequest(Struct, omit_defaults=True):
    trader: Optional[
        Annotated[
            Optional[definitions.TraderIdOrEmail],
            Meta(
                description="Request accounts from the perspective of this trader; if not specified, defaults to the caller user."
            ),
        ]
    ] = None
    """
    Request accounts from the perspective of this trader; if not specified, defaults to the caller user.
    """

    @staticmethod
    def get_response_type():
        return AccountsResponse

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Accounts/Accounts"

    @staticmethod
    def get_unary_type():
        return "unary"
