# generated by datamodel-codegen:
#   filename:  Accounts/AccountsRequest.json

from __future__ import annotations

from typing import Annotated, Optional

from msgspec import Meta, Struct

from .. import definitions


class AccountsRequest(Struct):
    trader: Optional[
        Annotated[
            Optional[definitions.TraderIdOrEmail],
            Meta(
                description='Request accounts from the perspective of this trader; if not specified, defaults to the caller user.'
            ),
        ]
    ] = None
    """
    Request accounts from the perspective of this trader; if not specified, defaults to the caller user.
    """

    @staticmethod
    def get_response_type():
        return "&RESPONSE_TYPE:AccountsRequest"

    @staticmethod
    def get_route() -> str:
        return "&ROUTE:AccountsRequest"

    @staticmethod
    def get_unary_type():
        return "&UNARY_TYPE:AccountsRequest"
