# generated by datamodel-codegen:
#   filename:  AccountsRequest.json

from __future__ import annotations
import grpc
import msgspec
from architect_py.grpc_client.Accounts.AccountsResponse import AccountsResponse
from architect_py.grpc_client.request import RequestUnary


from typing import Annotated, Optional

from msgspec import Meta, Struct

TraderIdOrEmail = str


class AccountsRequest(Struct):
    trader: Optional[
        Annotated[
            Optional[TraderIdOrEmail],
            Meta(
                description='Request accounts from the perspective of this trader; if not specified, defaults to the caller user.'
            ),
        ]
    ] = None

    @staticmethod
    def create_stub(channel: grpc.aio.Channel, encoder: msgspec.json.Encoder) -> grpc.aio.UnaryUnaryMultiCallable["AccountsRequest", AccountsResponse]:
        return channel.unary_unary(
            "/json.architect.Accounts/Accounts",
            request_serializer=encoder.encode,
            response_deserializer=lambda buf: msgspec.json.decode(
                buf, type=AccountsResponse
            ),
        )

AccountsRequestRequestHelper = RequestUnary(AccountsRequest, AccountsResponse, "/json.architect.Accounts/Accounts")
