[tool.ariadne-codegen]
target_package_path = "./architect_py"
target_package_name = "graphql_client"
client_name = "GraphQLClient"
schema_path = "schema.graphql"
queries_path = "queries.graphql"
base_client_name = "JuniperBaseClient"
base_client_file_path = "./templates/juniper_base_client.py"
files_to_include = ["./templates/exceptions.py"]
plugins = [
    "ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin",
    "ariadne_codegen.contrib.client_forward_refs.ClientForwardRefsPlugin",
    # adding a plugin for making __slots__ is not a good idea because it is not compatible with Pydantic
]

[tool.ariadne-codegen.scalars]
Decimal.type = "decimal.Decimal"

AccountName.type = "str"
ExecutionVenue.type = "str"
MarketdataVenue.type = "str"
OrderId.type = "str"
Product.type = "str"
TradableProduct.type = "architect_py.scalars.TradableProduct"
TradableProduct.serialize = "architect_py.scalars.serialize"
TradableProduct.deserialize = "architect_py.scalars.deserialize"
UserId.type = "str"
Uuid.type = "uuid.UUID"

Dir.type = "architect_py.scalars.OrderDir"
Dir.serialize = "architect_py.scalars.serialize"
Dir.deserialize = "architect_py.scalars.deserialize"

DateTime.type = "datetime.datetime"
DateTime.serialize = "architect_py.scalars.convert_datetime_to_utc_str"

Date.type = "datetime.date"