[tool.ariadne-codegen]
base_client_file_path = "./templates/juniper_base_client.py"
base_client_name = "JuniperBaseClient"
client_name = "GraphQLClient"
files_to_include = ["./templates/exceptions.py"]
plugins = [
    "ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin",
    "ariadne_codegen.contrib.client_forward_refs.ClientForwardRefsPlugin",
    # adding a plugin for making __slots__ is not a good idea because it is not compatible with Pydantic
]
queries_path = "queries.graphql"
schema_path = "schema.graphql"
target_package_name = "graphql_client"
target_package_path = "./architect_py"

[tool.ariadne-codegen.scalars]
Decimal.type = "decimal.Decimal"

AccountName.type = "str"
ExecutionVenue.type = "str"
MarketdataVenue.type = "str"
OrderId.type = "str"
Product.type = "str"

TradableProduct.parse = "architect_py.common_types.tradable_product.parse_tradable_product"
TradableProduct.type = "architect_py.common_types.TradableProduct"

UserId.type = "str"
Uuid.type = "uuid.UUID"

Dir.parse = "architect_py.common_types.order_dir.graphql_parse_order_dir"
Dir.serialize = "architect_py.common_types.order_dir.graphql_serialize_order_dir"
Dir.type = "architect_py.common_types.OrderDir" # enums auto serialize/parse

DateTime.serialize = "architect_py.common_types.scalars.convert_datetime_to_utc_str"
DateTime.type = "datetime.datetime"

Date.type = "datetime.date"
