[tool.ariadne-codegen]
async_client = false
target_package_path = "./architect_py"
target_package_name = "graphql_client"
client_name = "GraphQLClient"
schema_path = "schema.graphql"
queries_path = "queries.graphql"
base_client_name = "JuniperBaseClient"
base_client_file_path = "./templates/juniper_base_client.py"
files_to_include = ["./templates/exceptions.py"]
plugins = ["ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin"]

[tool.ariadne-codegen.scalars.Decimal]
type = "decimal.Decimal"