# generated by datamodel-codegen:
#   filename:  Folio/AccountSummaryRequest.json

from __future__ import annotations
from architect_py.grpc_client.Folio.AccountSummary import AccountSummary

from msgspec import Struct

from .. import definitions


class AccountSummaryRequest(Struct):
    account: definitions.AccountIdOrName

    @staticmethod
    def get_response_type():
        return ResponseType

    @staticmethod
    def get_route() -> str:
        return route

    @staticmethod
    def get_unary_type():
        return unary_type


ResponseType = AccountSummary
route = "/json.architect.Folio/AccountSummary"
unary_type = "unary"

