# generated by datamodel-codegen:
#   filename:  AccountSummariesRequest.json

from __future__ import annotations
from architect_py.grpc_client.Folio.AccountSummariesResponse import AccountSummariesResponse
from architect_py.grpc_client.request import RequestUnary


from typing import Annotated, List, Optional

from msgspec import Meta, Struct

AccountIdOrName = str


TraderIdOrEmail = str


class AccountSummariesRequest(Struct):
    accounts: Optional[
        Annotated[
            List[AccountIdOrName],
            Meta(
                description='If trader and accounts are both None, return all accounts for the user'
            ),
        ]
    ] = None
    trader: Optional[TraderIdOrEmail] = None


    @staticmethod
    def get_helper() -> RequestUnary:
        return AccountSummariesRequestHelper

AccountSummariesRequestHelper = RequestUnary(AccountSummariesRequest, AccountSummariesResponse, "/json.architect.Folio/AccountSummaries")

