# generated by datamodel-codegen:
#   filename:  AccountSummaryRequest.json

from __future__ import annotations
from architect_py.grpc_client.Folio.AccountSummary import AccountSummary
import grpc
import msgspec

from msgspec import Struct

AccountIdOrName = str


class AccountSummaryRequest(Struct):
    account: AccountIdOrName

    @staticmethod
    def create_stub(channel: grpc.aio.Channel) -> grpc.aio.UnaryUnaryMultiCallable:
        return channel.unary_unary(
            "/json.architect.Folio/AccountSummary",
            request_serializer=msgspec.json.encode,
            response_deserializer=lambda buf: msgspec.json.decode(
                buf, type=AccountSummary
            ),
        )
