# generated by datamodel-codegen:
#   filename:  Folio/AccountHistoryResponse.json

from __future__ import annotations

from typing import List

from msgspec import Struct

from .AccountSummary import AccountSummary


class AccountHistoryResponse(Struct, omit_defaults=True):
    history: List[AccountSummary]
