# generated by datamodel-codegen:
#   filename:  AccountSummaryRequest.json

from __future__ import annotations
from architect_py.grpc_client.Folio.AccountSummary import AccountSummary
from architect_py.grpc_client.request import RequestUnary


from msgspec import Struct

AccountIdOrName = str


class AccountSummaryRequest(Struct):
    account: AccountIdOrName

    @staticmethod
    def get_request_helper():
        return request_helper


request_helper = RequestUnary(AccountSummaryRequest, AccountSummary, "/json.architect.Folio/AccountSummary")

