# generated by datamodel-codegen:
#   filename:  AccountHistoryRequest.json

from __future__ import annotations
from architect_py.grpc_client.Folio.AccountHistoryResponse import AccountHistoryResponse
import grpc
import msgspec

from typing import Optional

from msgspec import Struct

AccountIdOrName = str


class AccountHistoryRequest(Struct):
    account: AccountIdOrName
    from_inclusive: Optional[str] = None
    to_exclusive: Optional[str] = None
def create_stub(channel: grpc.Channel | grpc.aio.Channel) -> None:
	channel.unary_unary(
		"/json.architect.Folio/AccountHistory",
		request_serializer=msgspec.json.encode,
		response_deserializer=lambda buf: msgspec.json.decode(
			buf, type=AccountHistoryResponse
		),
	)
