# generated by datamodel-codegen:
#   filename:  Folio/AccountHistoryRequest.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from msgspec import Struct

from .. import definitions


class AccountHistoryRequest(Struct):
    account: definitions.AccountIdOrName
    from_inclusive: Optional[datetime] = None
    to_exclusive: Optional[datetime] = None

    @staticmethod
    def get_response_type():
        return "&RESPONSE_TYPE:AccountHistoryRequest"

    @staticmethod
    def get_route() -> str:
        return "&ROUTE:AccountHistoryRequest"

    @staticmethod
    def get_unary_type():
        return "&UNARY_TYPE:AccountHistoryRequest"
