# generated by datamodel-codegen:
#   filename:  Folio/HistoricalOrdersResponse.json

from __future__ import annotations

from typing import List

from msgspec import Struct

from ..Oms import Order


class HistoricalOrdersResponse(Struct):
    orders: List[Order]
