# generated by datamodel-codegen:
#   filename:  Folio/HistoricalOrdersRequest.json

from __future__ import annotations
from architect_py.grpc_client.Folio.HistoricalOrdersResponse import (
    HistoricalOrdersResponse,
)

from typing import Annotated, List, Optional

from msgspec import Meta, Struct

from .. import definitions


class HistoricalOrdersRequest(Struct):
    account: Optional[definitions.AccountIdOrName] = None
    from_inclusive: Optional[str] = None
    limit: Optional[
        Annotated[Optional[int], Meta(description="Default maximum is 1000.", ge=0)]
    ] = None
    """
    Default maximum is 1000.
    """
    order_ids: Optional[
        Annotated[
            List[definitions.OrderId],
            Meta(description="if order_ids is not empty, the limit field is ignored"),
        ]
    ] = None
    """
    if order_ids is not empty, the limit field is ignored
    """
    parent_order_id: Optional[definitions.OrderId] = None
    to_exclusive: Optional[str] = None
    trader: Optional[definitions.TraderIdOrEmail] = None
    venue: Optional[str] = None

    @staticmethod
    def get_response_type():
        return ResponseType

    @staticmethod
    def get_route() -> str:
        return route

    @staticmethod
    def get_unary_type():
        return unary_type


ResponseType = HistoricalOrdersResponse
route = "/json.architect.Folio/HistoricalOrders"
unary_type = "unary"
