# generated by datamodel-codegen:
#   filename:  Symbology/SymbologyRequest.json

from __future__ import annotations

from msgspec import Struct


class SymbologyRequest(Struct):
    pass

    @staticmethod
    def get_response_type():
        return "&RESPONSE_TYPE:SymbologyRequest"

    @staticmethod
    def get_route() -> str:
        return "&ROUTE:SymbologyRequest"

    @staticmethod
    def get_unary_type():
        return "&UNARY_TYPE:SymbologyRequest"
