# generated by datamodel-codegen:
#   filename:  Symbology/SymbolsRequest.json

from __future__ import annotations
from architect_py.grpc_client.Symbology.SymbolsResponse import SymbolsResponse
from architect_py.grpc_client.request import RequestUnary


from msgspec import Struct


class SymbolsRequest(Struct):
    """
    List all symbols
    """

    @staticmethod
    def get_request_helper():
        return request_helper


request_helper = RequestUnary(SymbolsRequest, SymbolsResponse, "/json.architect.Symbology/Symbols")

