# generated by datamodel-codegen:
#   filename:  SymbologyRequest.json

from __future__ import annotations
from architect_py.grpc_client.Symbology.SymbologySnapshot import SymbologySnapshot
from architect_py.grpc_client.request import RequestUnary


from msgspec import Struct


class SymbologyRequest(Struct):
    pass


    @staticmethod
    def get_helper() -> RequestUnary:
        return SymbologyRequestHelper

SymbologyRequestHelper = RequestUnary(SymbologyRequest, SymbologySnapshot, "/json.architect.Symbology/Symbology")

