# generated by datamodel-codegen:
#   filename:  Symbology/UploadSymbologyResponse.json

from __future__ import annotations

from msgspec import Struct


class UploadSymbologyResponse(Struct, omit_defaults=True):
    pass
