# generated by datamodel-codegen:
#   filename:  Algo/AlgoOrderRequest.json

from __future__ import annotations
from architect_py.grpc.models.Algo.AlgoOrder import AlgoOrder

from msgspec import Struct

from .. import definitions


class AlgoOrderRequest(Struct, omit_defaults=True):
    """
    Get generic algo run status
    """

    algo_order_id: definitions.OrderId

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        algo_order_id: definitions.OrderId,
    ):
        return cls(
            algo_order_id,
        )

    def __str__(self) -> str:
        return f"AlgoOrderRequest(algo_order_id={self.algo_order_id})"

    @staticmethod
    def get_response_type():
        return AlgoOrder

    @staticmethod
    def get_unannotated_response_type():
        return AlgoOrder

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Algo/AlgoOrder"

    @staticmethod
    def get_rpc_method():
        return "unary"
