# generated by datamodel-codegen:
#   filename:  Algo/StopAlgoRequest.json

from __future__ import annotations
from architect_py.grpc.models.Algo.StopAlgoResponse import StopAlgoResponse

from msgspec import Struct

from .. import definitions


class StopAlgoRequest(Struct, omit_defaults=True):
    algo_order_id: definitions.OrderId

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        algo_order_id: definitions.OrderId,
    ):
        return cls(
            algo_order_id,
        )

    def __str__(self) -> str:
        return f"StopAlgoRequest(algo_order_id={self.algo_order_id})"

    @staticmethod
    def get_response_type():
        return StopAlgoResponse

    @staticmethod
    def get_unannotated_response_type():
        return StopAlgoResponse

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Algo/StopAlgo"

    @staticmethod
    def get_rpc_method():
        return "unary"
