# generated by datamodel-codegen:
#   filename:  Accounts/AccountRulesRequest.json

from __future__ import annotations
from architect_py.grpc.models.Accounts.AccountRulesResponse import AccountRulesResponse

from typing import Annotated, List, Optional

from msgspec import Meta, Struct


class AccountRulesRequest(Struct, omit_defaults=True):
    account_ids: Optional[
        Annotated[
            List[str],
            Meta(
                description="If specified, filter to only these specific account IDs."
            ),
        ]
    ] = None
    """
    If specified, filter to only these specific account IDs.
    """

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        account_ids: Optional[List[str]] = None,
    ):
        return cls(
            account_ids,
        )

    def __str__(self) -> str:
        return f"AccountRulesRequest(account_ids={self.account_ids})"

    @staticmethod
    def get_response_type():
        return AccountRulesResponse

    @staticmethod
    def get_unannotated_response_type():
        return AccountRulesResponse

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Accounts/AccountRules"

    @staticmethod
    def get_rpc_method():
        return "unary"
