# generated by datamodel-codegen:
#   filename:  Accounts/OpenPaperAccountResponse.json

from __future__ import annotations

from typing import Annotated, Optional

from msgspec import Meta, Struct


class OpenPaperAccountResponse(Struct, omit_defaults=True):
    success: bool
    account_id: Optional[
        Annotated[
            Optional[str],
            Meta(
                description="The ID of the newly created paper account (None if failed)"
            ),
        ]
    ] = None
    """
    The ID of the newly created paper account (None if failed)
    """
    error: Optional[
        Annotated[
            Optional[str], Meta(description="Error message if the operation failed")
        ]
    ] = None
    """
    Error message if the operation failed
    """

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        success: bool,
        account_id: Optional[str] = None,
        error: Optional[str] = None,
    ):
        return cls(
            success,
            account_id,
            error,
        )

    def __str__(self) -> str:
        return f"OpenPaperAccountResponse(success={self.success},account_id={self.account_id},error={self.error})"
