# generated by datamodel-codegen:
#   filename:  Accounts/ResetPaperAccountResponse.json

from __future__ import annotations

from msgspec import Struct


class ResetPaperAccountResponse(Struct, omit_defaults=True):
    pass

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
    ):
        return cls()

    def __str__(self) -> str:
        return f"ResetPaperAccountResponse()"
