# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import MarketSnapshotFields


class GetMarketSnapshot(BaseModel):
    market_snapshot: Optional["GetMarketSnapshotMarketSnapshot"] = Field(
        alias="marketSnapshot"
    )


class GetMarketSnapshotMarketSnapshot(MarketSnapshotFields):
    pass


GetMarketSnapshot.model_rebuild()
