# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import OrderLogFields


class GetOutOrders(BaseModel):
    outed_orders: List["GetOutOrdersOutedOrders"] = Field(alias="outedOrders")


class GetOutOrdersOutedOrders(OrderLogFields):
    pass


GetOutOrders.model_rebuild()
