# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel


class SubscribeTrades(BaseModel):
    trades: "SubscribeTradesTrades"


class SubscribeTradesTrades(BaseModel):
    time: Optional[Any]
    price: Any
    size: Any
    direction: Optional[Any]


SubscribeTrades.model_rebuild()
