# generated by datamodel-codegen:
#   filename:  Algo_CreateAlgoOrderRequest_for_TwapAlgo.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional

from msgspec import Meta, Struct

Decimal = str


class Dir(Enum):
    BUY = 'BUY'
    SELL = 'SELL'


HumanDuration = str


class OrderId(Struct):
    seqid: str
    seqno: Annotated[int, Meta(ge=0)]


class TwapParams(Struct):
    dir: Dir
    end_time: str
    execution_venue: str
    interval: HumanDuration
    quantity: Decimal
    reject_lockout: HumanDuration
    symbol: str
    take_through_frac: Optional[Decimal] = None


UserId = str


class CreateAlgoOrderRequestForTwapAlgo(Struct):
    algo_name: str
    params: TwapParams
    account: Optional[str] = None
    algo_order_id: Optional[OrderId] = None
    parent_order_id: Optional[OrderId] = None
    trader: Optional[UserId] = None
