# generated by datamodel-codegen:
#   filename:  Algo_CreateAlgoOrderRequest_for_TwapAlgo.json
#   timestamp: 2025-02-25T21:20:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from msgspec import Meta, Struct


class Dir(Enum):
    BUY = 'BUY'
    SELL = 'SELL'


class OrderId(Struct):
    seqid: str
    seqno: Annotated[int, Meta(ge=0)]


class TwapParams(Struct):
    dir: Dir
    end_time: str
    execution_venue: str
    interval: str
    quantity: str
    reject_lockout: str
    symbol: str
    take_through_frac: str | None = None


class CreateAlgoOrderRequestForTwapAlgo(Struct):
    algo_name: str
    params: TwapParams
    account: str | None = None
    algo_order_id: OrderId | None = None
    parent_order_id: OrderId | None = None
    trader: str | None = None
