# generated by datamodel-codegen:
#   filename:  Marketdata/HistoricalCandlesRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.HistoricalCandlesResponse import (
    HistoricalCandlesResponse,
)

from msgspec import Struct

from .. import definitions


class HistoricalCandlesRequest(Struct):
    candle_width: definitions.CandleWidth
    end_date: str
    start_date: str
    symbol: str

    @staticmethod
    def get_response_type():
        return ResponseType

    @staticmethod
    def get_route() -> str:
        return route

    @staticmethod
    def get_unary_type():
        return unary_type


ResponseType = HistoricalCandlesResponse
route = "/json.architect.Marketdata/HistoricalCandles"
unary_type = "unary"
