# generated by datamodel-codegen:
#   filename:  L1BookSnapshotRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.L1BookSnapshot import L1BookSnapshot
import grpc
import msgspec

from msgspec import Struct


class L1BookSnapshotRequest(Struct):
    symbol: str

    @staticmethod
    def create_stub(channel: grpc.aio.Channel, encoder: msgspec.json.Encoder) -> grpc.aio.UnaryUnaryMultiCallable["L1BookSnapshotRequest", L1BookSnapshot]:
        return channel.unary_unary(
            "/json.architect.Marketdata/L1BookSnapshot",
            request_serializer=encoder.encode,
            response_deserializer=lambda buf: msgspec.json.decode(
                buf, type=L1BookSnapshot
            ),
        )
