# generated by datamodel-codegen:
#   filename:  Marketdata/L1BookSnapshotRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.L1BookSnapshot import L1BookSnapshot

from msgspec import Struct


class L1BookSnapshotRequest(Struct, omit_defaults=True):
    symbol: str

    @staticmethod
    def get_response_type():
        return L1BookSnapshot

    @staticmethod
    def get_unannotated_response_type():
        return L1BookSnapshot

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Marketdata/L1BookSnapshot"

    @staticmethod
    def get_rpc_method():
        return "unary"
