# generated by datamodel-codegen:
#   filename:  Marketdata/L1BookSnapshotsRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.ArrayOfL1BookSnapshot import (
    ArrayOfL1BookSnapshot,
    L1BookSnapshot,
)

from typing import List, Optional

from msgspec import Struct


class L1BookSnapshotsRequest(Struct, omit_defaults=True):
    symbols: Optional[List[str]] = None

    # below is a constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        symbols: Optional[List[str]] = None,
    ):
        return cls(
            symbols,
        )

    def __str__(self) -> str:
        return f"L1BookSnapshotsRequest(symbols={self.symbols})"

    @staticmethod
    def get_response_type():
        return ArrayOfL1BookSnapshot

    @staticmethod
    def get_unannotated_response_type():
        return list[L1BookSnapshot]

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Marketdata/L1BookSnapshots"

    @staticmethod
    def get_rpc_method():
        return "unary"
