# generated by datamodel-codegen:
#   filename:  L2BookSnapshotRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.L2BookSnapshot import L2BookSnapshot
from architect_py.grpc_client.request import RequestUnary


from typing import Optional

from msgspec import Struct


class L2BookSnapshotRequest(Struct):
    symbol: str
    venue: Optional[str] = None


    @staticmethod
    def get_helper() -> RequestUnary:
        return L2BookSnapshotRequestHelper

L2BookSnapshotRequestHelper = RequestUnary(L2BookSnapshotRequest, L2BookSnapshot, "/json.architect.Marketdata/L2BookSnapshot")

