# generated by datamodel-codegen:
#   filename:  L2BookSnapshotRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.L2BookSnapshot import L2BookSnapshot
import grpc
import msgspec

from typing import Optional

from msgspec import Struct


class L2BookSnapshotRequest(Struct):
    symbol: str
    venue: Optional[str] = None

    @staticmethod
    def create_stub(channel: grpc.aio.Channel) -> grpc.aio.UnaryUnaryMultiCallable:
        return channel.unary_unary(
            "/json.architect.Marketdata/L2BookSnapshot",
            request_serializer=msgspec.json.encode,
            response_deserializer=lambda buf: msgspec.json.decode(
                buf, type=L2BookSnapshot
            ),
        )
