# generated by datamodel-codegen:
#   filename:  Marketdata/MarketStatusRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.MarketStatus import MarketStatus

from typing import Optional

from msgspec import Struct


class MarketStatusRequest(Struct):
    symbol: str
    venue: Optional[str] = None

    @staticmethod
    def get_response_type():
        return ResponseType

    @staticmethod
    def get_route() -> str:
        return route

    @staticmethod
    def get_unary_type():
        return unary_type


ResponseType = MarketStatus
route = "/json.architect.Marketdata/MarketStatus"
unary_type = "unary"
