# generated by datamodel-codegen:
#   filename:  Marketdata_SubscribeL2BookUpdatesRequest.json

from __future__ import annotations

from typing import Optional

from msgspec import Struct


class SubscribeL2BookUpdatesRequest(Struct):
    symbol: str
    venue: Optional[str] = None
