# generated by datamodel-codegen:
#   filename:  Marketdata/MarketStatusRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.MarketStatus import MarketStatus

from typing import Optional

from msgspec import Struct


class MarketStatusRequest(Struct, omit_defaults=True):
    symbol: str
    venue: Optional[str] = None

    # below is a constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        symbol: str,
        venue: Optional[str] = None,
    ):
        return cls(
            symbol,
            venue,
        )

    def __str__(self) -> str:
        return f"MarketStatusRequest(symbol={self.symbol},venue={self.venue})"

    @staticmethod
    def get_response_type():
        return MarketStatus

    @staticmethod
    def get_unannotated_response_type():
        return MarketStatus

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Marketdata/MarketStatus"

    @staticmethod
    def get_rpc_method():
        return "unary"
