# generated by datamodel-codegen:
#   filename:  SubscribeL2BookUpdatesRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.L2BookUpdate import L2BookUpdate
import grpc
import msgspec

from typing import Optional

from msgspec import Struct


class SubscribeL2BookUpdatesRequest(Struct):
    symbol: str
    venue: Optional[str] = None
def create_stub(channel: grpc.Channel | grpc.aio.Channel) -> None:
	channel.unary_stream(
		"/json.architect.Marketdata/SubscribeL2BookUpdates",
		request_serializer=msgspec.json.encode,
		response_deserializer=lambda buf: msgspec.json.decode(
			buf, type=L2BookUpdate
		),
	)
