# generated by datamodel-codegen:
#   filename:  Marketdata/SubscribeManyCandlesRequest.json

from __future__ import annotations

from typing import Annotated, List, Optional

from msgspec import Meta, Struct

from .. import definitions


class SubscribeManyCandlesRequest(Struct):
    candle_width: definitions.CandleWidth
    symbols: Optional[
        Annotated[
            List[str],
            Meta(description='If None, subscribe from all symbols on the feed'),
        ]
    ] = None
    """
    If None, subscribe from all symbols on the feed
    """
    venue: Optional[str] = None

    @staticmethod
    def get_response_type():
        return "&RESPONSE_TYPE:SubscribeManyCandlesRequest"

    @staticmethod
    def get_route() -> str:
        return "&ROUTE:SubscribeManyCandlesRequest"

    @staticmethod
    def get_unary_type():
        return "&UNARY_TYPE:SubscribeManyCandlesRequest"
