# generated by datamodel-codegen:
#   filename:  Marketdata/SubscribeTradesRequest.json

from __future__ import annotations

from typing import Annotated, Optional

from msgspec import Meta, Struct


class SubscribeTradesRequest(Struct):
    symbol: Optional[
        Annotated[
            Optional[str],
            Meta(description='If None, subscribe from all symbols on the feed'),
        ]
    ] = None
    """
    If None, subscribe from all symbols on the feed
    """
    venue: Optional[str] = None

    @staticmethod
    def get_response_type():
        return "&RESPONSE_TYPE:SubscribeTradesRequest"

    @staticmethod
    def get_route() -> str:
        return "&ROUTE:SubscribeTradesRequest"

    @staticmethod
    def get_unary_type():
        return "&UNARY_TYPE:SubscribeTradesRequest"
