# generated by datamodel-codegen:
#   filename:  SubscribeL2BookUpdatesRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.L2BookUpdate import L2BookUpdate
import grpc
import msgspec

from typing import Optional

from msgspec import Struct


class SubscribeL2BookUpdatesRequest(Struct):
    symbol: str
    venue: Optional[str] = None

    @staticmethod
    def create_stub(channel: grpc.aio.Channel) -> grpc.aio.UnaryStreamMultiCallable["SubscribeL2BookUpdatesRequest", L2BookUpdate]:
        return channel.unary_stream(
            "/json.architect.Marketdata/SubscribeL2BookUpdates",
            request_serializer=msgspec.json.encode,
            response_deserializer=lambda buf: msgspec.json.decode(
                buf, type=L2BookUpdate
            ),
        )
