# generated by datamodel-codegen:
#   filename:  Marketdata/SubscribeLiquidationsRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.Liquidation import Liquidation

from typing import List, Optional

from msgspec import Struct


class SubscribeLiquidationsRequest(Struct):
    symbols: Optional[List[str]] = None

    @staticmethod
    def get_response_type():
        return ResponseType

    @staticmethod
    def get_route() -> str:
        return route

    @staticmethod
    def get_unary_type():
        return unary_type


ResponseType = Liquidation
route = "/json.architect.Marketdata/SubscribeLiquidations"
unary_type = "stream"
