# generated by datamodel-codegen:
#   filename:  SubscribeLiquidationsRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.Liquidation import Liquidation
from architect_py.grpc_client.request import RequestStream


from typing import Optional, Sequence

from msgspec import Struct


class SubscribeLiquidationsRequest(Struct):
    symbols: Optional[Sequence[str]] = None


    @staticmethod
    def get_helper():
        return SubscribeLiquidationsRequestHelper

SubscribeLiquidationsRequestHelper = RequestStream(SubscribeLiquidationsRequest, Liquidation, "/json.architect.Marketdata/SubscribeLiquidations")

