# generated by datamodel-codegen:
#   filename:  Marketdata/TickerRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.Ticker import Ticker

from typing import Optional

from msgspec import Struct


class TickerRequest(Struct):
    symbol: str
    venue: Optional[str] = None

    @staticmethod
    def get_response_type():
        return ResponseType

    @staticmethod
    def get_route() -> str:
        return route

    @staticmethod
    def get_unary_type():
        return unary_type


ResponseType = Ticker
route = "/json.architect.Marketdata/Ticker"
unary_type = "unary"
