# generated by datamodel-codegen:
#   filename:  TickerRequest.json

from __future__ import annotations
from architect_py.grpc_client.Marketdata.Ticker import Ticker
import grpc
import msgspec

from typing import Optional

from msgspec import Struct


class TickerRequest(Struct):
    symbol: str
    venue: Optional[str] = None
def create_stub(channel: grpc.Channel | grpc.aio.Channel) -> None:
	channel.unary_unary(
		"/json.architect.Marketdata/Ticker",
		request_serializer=msgspec.json.encode,
		response_deserializer=lambda buf: msgspec.json.decode(
			buf, type=Ticker
		),
	)
