# generated by datamodel-codegen:
#   filename:  Marketdata/TickerUpdate.json

from __future__ import annotations

from typing import Annotated, Union

from msgspec import Meta

from .Ticker import Ticker


class Snapshot(Ticker, omit_defaults=True, tag_field="t", tag="s"):
    pass


class Diff(Ticker, omit_defaults=True, tag_field="t", tag="d"):
    pass


TickerUpdate = Annotated[Union[Snapshot, Diff], Meta(title="TickerUpdate")]
