# generated by datamodel-codegen:
#   filename:  Folio/PositionsResponse.json

from __future__ import annotations

from typing import List

from msgspec import Struct

from .. import definitions


class PositionsResponse(Struct, omit_defaults=True):
    positions: List[definitions.PositionSummary]

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        positions: List[definitions.PositionSummary],
    ):
        return cls(
            positions,
        )

    def __str__(self) -> str:
        return f"PositionsResponse(positions={self.positions})"
