# generated by datamodel-codegen:
#   filename:  Oms/Cancel.json

from __future__ import annotations

from typing import Annotated, Optional

from msgspec import Meta, Struct

from .. import definitions


class Cancel(Struct):
    id: definitions.OrderId
    o: definitions.CancelStatus
    tn: Annotated[int, Meta(ge=0)]
    ts: int
    xid: str
    r: Optional[str] = None
