# generated by datamodel-codegen:
#   filename:  Oms/CancelAllOrdersRequest.json

from __future__ import annotations
from architect_py.grpc_client.Oms.CancelAllOrdersResponse import CancelAllOrdersResponse

from typing import Optional

from msgspec import Struct

from .. import definitions


class CancelAllOrdersRequest(Struct, omit_defaults=True):
    id: str
    account: Optional[definitions.AccountIdOrName] = None
    execution_venue: Optional[str] = None
    trader: Optional[definitions.TraderIdOrEmail] = None

    @staticmethod
    def get_response_type():
        return CancelAllOrdersResponse

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Oms/CancelAllOrders"

    @staticmethod
    def get_unary_type():
        return "unary"
