# generated by datamodel-codegen:
#   filename:  CancelAllOrdersRequest.json

from __future__ import annotations
from architect_py.grpc_client.Oms.CancelAllOrdersResponse import CancelAllOrdersResponse
import grpc
import msgspec

from typing import Optional

from msgspec import Struct

AccountIdOrName = str


TraderIdOrEmail = str


class CancelAllOrdersRequest(Struct):
    id: str
    account: Optional[AccountIdOrName] = None
    execution_venue: Optional[str] = None
    trader: Optional[TraderIdOrEmail] = None
def create_stub(channel: grpc.Channel | grpc.aio.Channel) -> None:
	channel.unary_unary(
		"/json.architect.Oms/CancelAllOrders",
		request_serializer=msgspec.json.encode,
		response_deserializer=lambda buf: msgspec.json.decode(
			buf, type=CancelAllOrdersResponse
		),
	)
