# generated by datamodel-codegen:
#   filename:  OpenOrdersRequest.json

from __future__ import annotations
from architect_py.grpc_client.Oms.OpenOrdersResponse import OpenOrdersResponse
import grpc
import msgspec

from typing import Annotated, List, Optional

from msgspec import Meta, Struct

AccountIdOrName = str


class OrderId(Struct):
    seqid: str
    seqno: Annotated[int, Meta(ge=0)]


TraderIdOrEmail = str


class OpenOrdersRequest(Struct):
    account: Optional[AccountIdOrName] = None
    order_ids: Optional[List[OrderId]] = None
    parent_order_id: Optional[OrderId] = None
    symbol: Optional[str] = None
    trader: Optional[TraderIdOrEmail] = None
    venue: Optional[str] = None
def create_stub(channel: grpc.Channel | grpc.aio.Channel) -> None:
	channel.unary_unary(
		"/json.architect.Oms/OpenOrders",
		request_serializer=msgspec.json.encode,
		response_deserializer=lambda buf: msgspec.json.decode(
			buf, type=OpenOrdersResponse
		),
	)
