# generated by datamodel-codegen:
#   filename:  Oms/PendingCancelsRequest.json

from __future__ import annotations
from architect_py.grpc_client.Oms.PendingCancelsResponse import PendingCancelsResponse

from typing import List, Optional

from msgspec import Struct

from .. import definitions


class PendingCancelsRequest(Struct):
    account: Optional[definitions.AccountIdOrName] = None
    cancel_ids: Optional[List[str]] = None
    symbol: Optional[str] = None
    trader: Optional[definitions.TraderIdOrEmail] = None
    venue: Optional[str] = None

    @staticmethod
    def get_response_type():
        return ResponseType

    @staticmethod
    def get_route() -> str:
        return route

    @staticmethod
    def get_unary_type():
        return unary_type


ResponseType = PendingCancelsResponse
route = "/json.architect.Oms/PendingCancels"
unary_type = "unary"

