# generated by datamodel-codegen:
#   filename:  Oms/PlaceOrderRequest.json

from __future__ import annotations
from architect_py.grpc_client.Oms.Order import Order

from typing import Annotated, Literal, Optional, Union

from msgspec import Meta, Struct

from .. import definitions


class PlaceOrderRequest1(Struct):
    d: Annotated[definitions.Dir, Meta(title='dir')]
    q: Annotated[definitions.DecimalModel, Meta(title='quantity')]
    s: Annotated[str, Meta(title='symbol')]
    tif: Annotated[definitions.TimeInForce, Meta(title='time_in_force')]
    k: Literal['LIMIT']
    p: Annotated[definitions.DecimalModel, Meta(title='limit_price')]
    po: Annotated[bool, Meta(title='post_only')]
    a: Optional[
        Annotated[Optional[definitions.AccountIdOrName], Meta(title='account')]
    ] = None
    id: Optional[
        Annotated[
            Optional[definitions.OrderId],
            Meta(
                description="If not specified, one will be generated for you; note, in that case, you won't know for sure if the specific request went through."
            ),
        ]
    ] = None
    """
    If not specified, one will be generated for you; note, in that case, you won't know for sure if the specific request went through.
    """
    pid: Optional[Annotated[Optional[definitions.OrderId], Meta(title='parent_id')]] = (
        None
    )
    src: Optional[
        Annotated[Optional[definitions.OrderSource], Meta(title='source')]
    ] = None
    u: Optional[
        Annotated[Optional[definitions.TraderIdOrEmail], Meta(title='trader')]
    ] = None
    x: Optional[Annotated[Optional[str], Meta(title='execution_venue')]] = None


class PlaceOrderRequest2(Struct):
    d: Annotated[definitions.Dir, Meta(title='dir')]
    q: Annotated[definitions.DecimalModel, Meta(title='quantity')]
    s: Annotated[str, Meta(title='symbol')]
    tif: Annotated[definitions.TimeInForce, Meta(title='time_in_force')]
    k: Literal['STOP_LOSS_LIMIT']
    p: Annotated[definitions.DecimalModel, Meta(title='limit_price')]
    tp: Annotated[definitions.DecimalModel, Meta(title='trigger_price')]
    a: Optional[
        Annotated[Optional[definitions.AccountIdOrName], Meta(title='account')]
    ] = None
    id: Optional[
        Annotated[
            Optional[definitions.OrderId],
            Meta(
                description="If not specified, one will be generated for you; note, in that case, you won't know for sure if the specific request went through."
            ),
        ]
    ] = None
    """
    If not specified, one will be generated for you; note, in that case, you won't know for sure if the specific request went through.
    """
    pid: Optional[Annotated[Optional[definitions.OrderId], Meta(title='parent_id')]] = (
        None
    )
    src: Optional[
        Annotated[Optional[definitions.OrderSource], Meta(title='source')]
    ] = None
    u: Optional[
        Annotated[Optional[definitions.TraderIdOrEmail], Meta(title='trader')]
    ] = None
    x: Optional[Annotated[Optional[str], Meta(title='execution_venue')]] = None


class PlaceOrderRequest3(Struct):
    d: Annotated[definitions.Dir, Meta(title='dir')]
    q: Annotated[definitions.DecimalModel, Meta(title='quantity')]
    s: Annotated[str, Meta(title='symbol')]
    tif: Annotated[definitions.TimeInForce, Meta(title='time_in_force')]
    k: Literal['TAKE_PROFIT_LIMIT']
    p: Annotated[definitions.DecimalModel, Meta(title='limit_price')]
    tp: Annotated[definitions.DecimalModel, Meta(title='trigger_price')]
    a: Optional[
        Annotated[Optional[definitions.AccountIdOrName], Meta(title='account')]
    ] = None
    id: Optional[
        Annotated[
            Optional[definitions.OrderId],
            Meta(
                description="If not specified, one will be generated for you; note, in that case, you won't know for sure if the specific request went through."
            ),
        ]
    ] = None
    """
    If not specified, one will be generated for you; note, in that case, you won't know for sure if the specific request went through.
    """
    pid: Optional[Annotated[Optional[definitions.OrderId], Meta(title='parent_id')]] = (
        None
    )
    src: Optional[
        Annotated[Optional[definitions.OrderSource], Meta(title='source')]
    ] = None
    u: Optional[
        Annotated[Optional[definitions.TraderIdOrEmail], Meta(title='trader')]
    ] = None
    x: Optional[Annotated[Optional[str], Meta(title='execution_venue')]] = None


PlaceOrderRequest = Annotated[
    Union[PlaceOrderRequest1, PlaceOrderRequest2, PlaceOrderRequest3],
    Meta(title='PlaceOrderRequest'),
]


ResponseType = Order
route = "/json.architect.Oms/PlaceOrder"
unary_type = "unary"

