# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class CancelOrders(BaseModel):
    cancel_orders: List[str] = Field(alias="cancelOrders")
