# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from .base_model import BaseModel


class GetAccounts(BaseModel):
    accounts: List["GetAccountsAccounts"]


class GetAccountsAccounts(BaseModel):
    id: str
    name: str


GetAccounts.model_rebuild()
