# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime
from decimal import Decimal
from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProductFields


class GetBalancesForCpty(BaseModel):
    account_summaries_for_cpty: "GetBalancesForCptyAccountSummariesForCpty" = Field(
        alias="accountSummariesForCpty"
    )


class GetBalancesForCptyAccountSummariesForCpty(BaseModel):
    snapshot_ts: datetime = Field(alias="snapshotTs")
    by_account: List["GetBalancesForCptyAccountSummariesForCptyByAccount"] = Field(
        alias="byAccount"
    )


class GetBalancesForCptyAccountSummariesForCptyByAccount(BaseModel):
    balances: List["GetBalancesForCptyAccountSummariesForCptyByAccountBalances"]


class GetBalancesForCptyAccountSummariesForCptyByAccountBalances(BaseModel):
    product: Optional[
        "GetBalancesForCptyAccountSummariesForCptyByAccountBalancesProduct"
    ]
    amount: Optional[Decimal]


class GetBalancesForCptyAccountSummariesForCptyByAccountBalancesProduct(ProductFields):
    pass


GetBalancesForCpty.model_rebuild()
GetBalancesForCptyAccountSummariesForCpty.model_rebuild()
GetBalancesForCptyAccountSummariesForCptyByAccount.model_rebuild()
GetBalancesForCptyAccountSummariesForCptyByAccountBalances.model_rebuild()
