# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import datetime
from decimal import Decimal
from typing import Optional

from pydantic import Field

from architect_py.scalars import OrderDir

from .base_model import BaseModel


class GetPovOrder(BaseModel):
    pov_order: Optional["GetPovOrderPovOrder"] = Field(alias="povOrder")


class GetPovOrderPovOrder(BaseModel):
    name: str
    order_id: str = Field(alias="orderId")
    market_id: str = Field(alias="marketId")
    dir: OrderDir
    target_volume_frac: Decimal = Field(alias="targetVolumeFrac")
    min_order_quantity: Decimal = Field(alias="minOrderQuantity")
    max_quantity: Decimal = Field(alias="maxQuantity")
    end_time: datetime = Field(alias="endTime")
    account_id: Optional[str] = Field(alias="accountId")
    take_through_frac: Optional[Decimal] = Field(alias="takeThroughFrac")


GetPovOrder.model_rebuild()
