# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AlgoKind


class GetAlgoOrder(BaseModel):
    algo_order: Optional["GetAlgoOrderAlgoOrder"] = Field(alias="algoOrder")


class GetAlgoOrderAlgoOrder(BaseModel):
    order_id: str = Field(alias="orderId")
    trader: str
    account: Optional[str]
    algo: AlgoKind
    parent_order_id: Optional[str] = Field(alias="parentOrderId")
    markets: List[str]


GetAlgoOrder.model_rebuild()
