# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProductFields


class GetBalancesForCpty(BaseModel):
    balances_for_cpty: List["GetBalancesForCptyBalancesForCpty"] = Field(
        alias="balancesForCpty"
    )


class GetBalancesForCptyBalancesForCpty(BaseModel):
    snapshot_ts: Any = Field(alias="snapshotTs")
    product: Optional["GetBalancesForCptyBalancesForCptyProduct"]
    amount: Any


class GetBalancesForCptyBalancesForCptyProduct(ProductFields):
    pass


GetBalancesForCpty.model_rebuild()
GetBalancesForCptyBalancesForCpty.model_rebuild()
