# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import ExecutionInfoFields


class GetExecutionInfosQuery(BaseModel):
    symbology: "GetExecutionInfosQuerySymbology"


class GetExecutionInfosQuerySymbology(BaseModel):
    execution_infos: List["GetExecutionInfosQuerySymbologyExecutionInfos"] = Field(
        alias="executionInfos"
    )


class GetExecutionInfosQuerySymbologyExecutionInfos(ExecutionInfoFields):
    pass


GetExecutionInfosQuery.model_rebuild()
GetExecutionInfosQuerySymbology.model_rebuild()
