# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import MarketTickerFields


class GetMarketSnapshotsQuery(BaseModel):
    marketdata: "GetMarketSnapshotsQueryMarketdata"


class GetMarketSnapshotsQueryMarketdata(BaseModel):
    tickers: List["GetMarketSnapshotsQueryMarketdataTickers"]


class GetMarketSnapshotsQueryMarketdataTickers(MarketTickerFields):
    pass


GetMarketSnapshotsQuery.model_rebuild()
GetMarketSnapshotsQueryMarketdata.model_rebuild()
