# Generated by ariadne-codegen
# Source: queries.graphql

from datetime import date
from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetFirstNoticeDateQuery(BaseModel):
    symbology: "GetFirstNoticeDateQuerySymbology"


class GetFirstNoticeDateQuerySymbology(BaseModel):
    product_info: Optional["GetFirstNoticeDateQuerySymbologyProductInfo"] = Field(
        alias="productInfo"
    )


class GetFirstNoticeDateQuerySymbologyProductInfo(BaseModel):
    first_notice_date: Optional[date] = Field(alias="firstNoticeDate")


GetFirstNoticeDateQuery.model_rebuild()
GetFirstNoticeDateQuerySymbology.model_rebuild()
