# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import ProductInfoFields


class GetProductInfosQuery(BaseModel):
    symbology: "GetProductInfosQuerySymbology"


class GetProductInfosQuerySymbology(BaseModel):
    product_infos: List["GetProductInfosQuerySymbologyProductInfos"] = Field(
        alias="productInfos"
    )


class GetProductInfosQuerySymbologyProductInfos(ProductInfoFields):
    pass


GetProductInfosQuery.model_rebuild()
GetProductInfosQuerySymbology.model_rebuild()
