# Generated by ariadne-codegen
# Source: queries.graphql

from decimal import Decimal
from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetMargin(BaseModel):
    market: Optional["GetMarginMarket"]


class GetMarginMarket(BaseModel):
    initial_margin: Optional[Decimal] = Field(alias="initialMargin")
    maintenance_margin: Optional[Decimal] = Field(alias="maintenanceMargin")


GetMargin.model_rebuild()
