# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class SendSmartOrderRouterAlgoRequest(BaseModel):
    create_smart_order_router_algo: Any = Field(alias="createSmartOrderRouterAlgo")
