# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class SendOrders(BaseModel):
    create_orders: List[str] = Field(alias="createOrders")
