# generated by datamodel-codegen:
#   filename:  Cpty/CptyRequest.json

from __future__ import annotations
from architect_py.grpc_client.Cpty.CptyResponse import CptyResponse

from typing import Annotated, Union

from msgspec import Meta

from .. import definitions
from ..Oms.Order import Order

CptyRequest = Annotated[
    Union[definitions.CptyLoginRequest, definitions.CptyLogoutRequest, Order],
    Meta(title="CptyRequest"),
]
