# generated by datamodel-codegen:
#   filename:  Cpty/CptyRequest.json

from __future__ import annotations
from architect_py.grpc_client.Cpty.CptyResponse import CptyResponse

from typing import Annotated, Optional, Union

from msgspec import Meta, Struct

from .. import definitions
from ..Oms.Cancel import Cancel
from ..Oms.Order import Order


class CancelOrder(Struct):
    cancel: Cancel
    original_order: Optional[Order] = None


CptyRequest = Annotated[
    Union[
        definitions.CptyLoginRequest, definitions.CptyLogoutRequest, Order, CancelOrder
    ],
    Meta(title="CptyRequest"),
]
