# generated by datamodel-codegen:
#   filename:  OptionsMarketdata/OptionsChainRequest.json

from __future__ import annotations
from architect_py.grpc.models.OptionsMarketdata.OptionsChain import OptionsChain

from datetime import date

from msgspec import Struct


class OptionsChainRequest(Struct, omit_defaults=True):
    expiration: date
    underlying: str

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        expiration: date,
        underlying: str,
    ):
        return cls(
            expiration,
            underlying,
        )

    def __str__(self) -> str:
        return f"OptionsChainRequest(expiration={self.expiration},underlying={self.underlying})"

    @staticmethod
    def get_response_type():
        return OptionsChain

    @staticmethod
    def get_unannotated_response_type():
        return OptionsChain

    @staticmethod
    def get_route() -> str:
        return "/json.architect.OptionsMarketdata/OptionsChain"

    @staticmethod
    def get_rpc_method():
        return "unary"
