# generated by datamodel-codegen:
#   filename:  Auth/AuthInfoResponse.json

from __future__ import annotations

from typing import Optional

from msgspec import Struct

from .. import definitions


class AuthInfoResponse(Struct, omit_defaults=True):
    original_user_id: Optional[definitions.UserId] = None
    user_id: Optional[definitions.UserId] = None

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        original_user_id: Optional[definitions.UserId] = None,
        user_id: Optional[definitions.UserId] = None,
    ):
        return cls(
            original_user_id,
            user_id,
        )

    def __str__(self) -> str:
        return f"AuthInfoResponse(original_user_id={self.original_user_id},user_id={self.user_id})"
