# generated by datamodel-codegen:
#   filename:  Auth/LicenseInfoResponse.json

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from msgspec import Meta, Struct


class LicenseInfoResponse(Struct, omit_defaults=True):
    not_after: datetime
    not_before: datetime
    pubkey: Annotated[str, Meta(description="PEM-encoded public key")]
    """
    PEM-encoded public key
    """
    subject: str

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        not_after: datetime,
        not_before: datetime,
        pubkey: str,
        subject: str,
    ):
        return cls(
            not_after,
            not_before,
            pubkey,
            subject,
        )

    def __str__(self) -> str:
        return f"LicenseInfoResponse(not_after={self.not_after},not_before={self.not_before},pubkey={self.pubkey},subject={self.subject})"
