# generated by datamodel-codegen:
#   filename:  Oms/BatchCancelOrdersRequest.json

from __future__ import annotations
from architect_py.grpc.models.Oms.BatchCancelOrdersResponse import (
    BatchCancelOrdersResponse,
)

from typing import List

from msgspec import Struct

from .CancelOrderRequest import CancelOrderRequest


class BatchCancelOrdersRequest(Struct, omit_defaults=True):
    """
    Batch cancel orders.  Depending on the cpty, their may be different semantics on how the batch cancel is handled.
    """

    cancel_orders: List[CancelOrderRequest]

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        cancel_orders: List[CancelOrderRequest],
    ):
        return cls(
            cancel_orders,
        )

    def __str__(self) -> str:
        return f"BatchCancelOrdersRequest(cancel_orders={self.cancel_orders})"

    @staticmethod
    def get_response_type():
        return BatchCancelOrdersResponse

    @staticmethod
    def get_unannotated_response_type():
        return BatchCancelOrdersResponse

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Oms/BatchCancelOrders"

    @staticmethod
    def get_rpc_method():
        return "unary"
