# generated by datamodel-codegen:
#   filename:  Oms/GetOrdersRequest.json

from __future__ import annotations
from architect_py.grpc.models.Oms.GetOrdersResponse import GetOrdersResponse

from typing import List

from msgspec import Struct

from .. import definitions


class GetOrdersRequest(Struct, omit_defaults=True):
    order_ids: List[definitions.OrderId]

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        order_ids: List[definitions.OrderId],
    ):
        return cls(
            order_ids,
        )

    def __str__(self) -> str:
        return f"GetOrdersRequest(order_ids={self.order_ids})"

    @staticmethod
    def get_response_type():
        return GetOrdersResponse

    @staticmethod
    def get_unannotated_response_type():
        return GetOrdersResponse

    @staticmethod
    def get_route() -> str:
        return "/json.architect.Oms/GetOrders"

    @staticmethod
    def get_rpc_method():
        return "unary"
