# generated by datamodel-codegen:
#   filename:  Folio_AccountSummaryRequest.json
#   timestamp: 2025-02-26T07:59:54+00:00

from __future__ import annotations

from msgspec import Struct


class AccountSummaryRequest(Struct):
    account: str
