# generated by datamodel-codegen:
#   filename:  Folio_AccountSummariesRequest.json
#   timestamp: 2025-02-26T08:01:07+00:00

from __future__ import annotations

from typing import List

from msgspec import Struct


class AccountSummariesRequest(Struct):
    accounts: List[str] | None = None
    trader: str | None = None
