# generated by datamodel-codegen:
#   filename:  Folio_AccountHistoryRequest.json
#   timestamp: 2025-02-26T08:01:07+00:00

from __future__ import annotations

from msgspec import Struct


class AccountHistoryRequest(Struct):
    account: str
    from_inclusive: str | None = None
    to_exclusive: str | None = None
