# generated by datamodel-codegen:
#   filename:  DropcopyRequest.json

from __future__ import annotations
from architect_py.grpc_client.Orderflow.Dropcopy import Dropcopy
import grpc
import msgspec

from typing import Optional

from msgspec import Struct

AccountIdOrName = str


TraderIdOrEmail = str


class DropcopyRequest(Struct):
    aberrant_fills: Optional[bool] = False
    account: Optional[AccountIdOrName] = None
    execution_venue: Optional[str] = None
    fills: Optional[bool] = True
    orders: Optional[bool] = False
    trader: Optional[TraderIdOrEmail] = None
def create_stub(channel: grpc.Channel | grpc.aio.Channel) -> None:
	channel.unary_stream(
		"/json.architect.Orderflow/Dropcopy",
		request_serializer=msgspec.json.encode,
		response_deserializer=lambda buf: msgspec.json.decode(
			buf, type=Dropcopy
		),
	)
