# generated by datamodel-codegen:
#   filename:  Orderflow/OrderflowRequest.json

from __future__ import annotations
from architect_py.grpc_client.Orderflow.Orderflow import Orderflow
from architect_py.grpc_client.Orderflow.Orderflow import Orderflow

from typing import Annotated, Union

from msgspec import Meta

from ..Oms.CancelAllOrdersRequest import CancelAllOrdersRequest
from ..Oms.CancelOrderRequest import CancelOrderRequest
from ..Oms.PlaceOrderRequest import PlaceOrderRequest


class PlaceOrder(PlaceOrderRequest, omit_defaults=True, tag_field="t", tag="p"):
    pass


class CancelOrder(CancelOrderRequest, omit_defaults=True, tag_field="t", tag="x"):
    pass


class CancelAllOrders(
    CancelAllOrdersRequest, omit_defaults=True, tag_field="t", tag="xo"
):
    pass


OrderflowRequest = Annotated[
    Union[PlaceOrder, CancelOrder, CancelAllOrders], Meta(title="OrderflowRequest")
]


unary = "duplex_stream"
response_type = Orderflow
route = "/json.architect.Orderflow/Orderflow"
