# generated by datamodel-codegen:
#   filename:  Symbology_PruneExpiredSymbolsResponse.json
#   timestamp: 2025-02-26T08:01:01+00:00

from __future__ import annotations

from msgspec import Struct


class PruneExpiredSymbolsResponse(Struct):
    pass
