# generated by datamodel-codegen:
#   filename:  Symbology_SymbologyRequest.json
#   timestamp: 2025-02-25T21:20:52+00:00

from __future__ import annotations

from msgspec import Struct


class SymbologyRequest(Struct):
    pass
