# generated by datamodel-codegen:
#   filename:  Symbology_PruneExpiredSymbolsResponse.json
#   timestamp: 2025-02-25T21:20:53+00:00

from __future__ import annotations

from msgspec import Struct


class PruneExpiredSymbolsResponse(Struct):
    pass
