# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class CancelAllOrders(BaseModel):
    cancel_all_orders: Optional[Any] = Field(alias="cancelAllOrders")
