# generated by datamodel-codegen:
#   filename:  Orderflow_SubscribeOrderflowRequest.json

from __future__ import annotations

from typing import Optional

from msgspec import Struct

AccountIdOrName = str


TraderIdOrEmail = str


class SubscribeOrderflowRequest(Struct):
    account: Optional[AccountIdOrName] = None
    execution_venue: Optional[str] = None
    trader: Optional[TraderIdOrEmail] = None
