# generated by datamodel-codegen:
#   filename:  Marketdata_L2BookSnapshot.json

from __future__ import annotations

from typing import Annotated, List

from msgspec import Meta, Struct

Decimal = str


AItem = List[Decimal]


BItem = List[Decimal]


class L2BookSnapshot(Struct):
    a: Annotated[List[AItem], Meta(title='asks')]
    b: Annotated[List[BItem], Meta(title='bids')]
    sid: Annotated[int, Meta(ge=0, title='sequence_id')]
    sn: Annotated[int, Meta(ge=0, title='sequence_number')]
    tn: Annotated[int, Meta(ge=0, title='timestamp_ns')]
    ts: Annotated[int, Meta(title='timestamp')]
