# generated by datamodel-codegen:
#   filename:  Marketdata_SubscribeCandlesRequest.json
#   timestamp: 2025-02-25T21:20:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, List

from msgspec import Meta, Struct


class CandleWidth(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_4 = 4
    integer_8 = 8
    integer_16 = 16
    integer_32 = 32


class SubscribeCandlesRequest(Struct):
    symbol: str
    candle_widths: (
        Annotated[
            List[CandleWidth],
            Meta(description='If None, subscribe from all candle widths on the feed'),
        ]
        | None
    ) = None
    venue: str | None = None
