# generated by datamodel-codegen:
#   filename:  Marketdata_SubscribeCandlesRequest.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, List, Optional

from msgspec import Meta, Struct


class CandleWidth(int, Enum):
    integer_1 = 1
    integer_2 = 2
    integer_4 = 4
    integer_8 = 8
    integer_16 = 16
    integer_32 = 32


class SubscribeCandlesRequest(Struct):
    symbol: str
    candle_widths: Optional[
        Annotated[
            List[CandleWidth],
            Meta(description='If None, subscribe from all candle widths on the feed'),
        ]
    ] = None
    venue: Optional[str] = None
