# generated by datamodel-codegen:
#   filename:  Marketdata_MarketStatus.json
#   timestamp: 2025-02-26T08:00:57+00:00

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class MarketStatus(Struct):
    s: Annotated[str, Meta(title='symbol')]
    is_quoting: bool | None = None
    is_trading: bool | None = None
