# generated by datamodel-codegen:
#   filename:  Marketdata_L1BookSnapshot.json

from __future__ import annotations

from typing import Annotated, List, Optional

from msgspec import Meta, Struct

Decimal = str


class L1BookSnapshot(Struct):
    s: Annotated[str, Meta(title='symbol')]
    tn: Annotated[int, Meta(ge=0, title='timestamp_ns')]
    ts: Annotated[int, Meta(title='timestamp')]
    a: Optional[Annotated[List[Decimal], Meta(title='best_ask')]] = None
    b: Optional[Annotated[List[Decimal], Meta(title='best_bid')]] = None
