# generated by datamodel-codegen:
#   filename:  Marketdata_L1BookSnapshotRequest.json

from __future__ import annotations

from msgspec import Struct


class L1BookSnapshotRequest(Struct):
    symbol: str
