# generated by datamodel-codegen:
#   filename:  Accounts_AccountsRequest.json
#   timestamp: 2025-02-26T08:01:05+00:00

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class AccountsRequest(Struct):
    trader: (
        Annotated[
            str | None,
            Meta(
                description='Request accounts from the perspective of this trader; if not specified, defaults to the caller user.'
            ),
        ]
        | None
    ) = None
    """
    Request accounts from the perspective of this trader; if not specified, defaults to the caller user.
    """
