# generated by datamodel-codegen:
#   filename:  Boss/MarginCallsResponse.json

from __future__ import annotations

from typing import List

from msgspec import Struct

from .. import definitions


class MarginCallsResponse(Struct, omit_defaults=True):
    margin_calls: List[definitions.MarginCall]

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        margin_calls: List[definitions.MarginCall],
    ):
        return cls(
            margin_calls,
        )

    def __str__(self) -> str:
        return f"MarginCallsResponse(margin_calls={self.margin_calls})"
