# generated by datamodel-codegen:
#   filename:  Boss/OptionsTransactionsResponse.json

from __future__ import annotations

from typing import List

from msgspec import Struct

from .. import definitions


class OptionsTransactionsResponse(Struct, omit_defaults=True):
    options_transactions: List[definitions.OptionsTransaction]

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        options_transactions: List[definitions.OptionsTransaction],
    ):
        return cls(
            options_transactions,
        )

    def __str__(self) -> str:
        return f"OptionsTransactionsResponse(options_transactions={self.options_transactions})"
