# generated by datamodel-codegen:
#   filename:  Boss/RqdAccountStatisticsResponse.json

from __future__ import annotations

from msgspec import Struct

from .. import definitions


class RqdAccountStatisticsResponse(Struct, omit_defaults=True):
    rqd_account_statistics: definitions.RqdAccountStatistics

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        rqd_account_statistics: definitions.RqdAccountStatistics,
    ):
        return cls(
            rqd_account_statistics,
        )

    def __str__(self) -> str:
        return f"RqdAccountStatisticsResponse(rqd_account_statistics={self.rqd_account_statistics})"
