# generated by datamodel-codegen:
#   filename:  Boss/StatementUrlResponse.json

from __future__ import annotations

from msgspec import Struct


class StatementUrlResponse(Struct, omit_defaults=True):
    statement_url: str

    # Constructor that takes all field titles as arguments for convenience
    @classmethod
    def new(
        cls,
        statement_url: str,
    ):
        return cls(
            statement_url,
        )

    def __str__(self) -> str:
        return f"StatementUrlResponse(statement_url={self.statement_url})"
